import Config

# Configure your database
config :hydra_srt, HydraSrt.Repo,
  database: Path.expand("../hydra_srt_dev.db", __DIR__),
  pool_size: 5,
  journal_mode: :wal,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :hydra_srt, HydraSrtWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9re8gLwrcmLnNcUbxe8xgKSCNfm8gIpgoBBiCXhV0dVfJMB8DVFB3QQJwOye0iIo",
  watchers: [
    # Run Vite directly instead of through `npm run dev`.
    # This avoids orphaned node/vite processes that can keep port 5173 busy after Ctrl+C.
    node: ["./node_modules/vite/bin/vite.js", cd: Path.expand("../web_app", __DIR__)]
  ]

config :hydra_srt,
  api_auth_username: System.get_env("API_AUTH_USERNAME") || "admin",
  api_auth_password: System.get_env("API_AUTH_PASSWORD") || "password123",
  telemetry: [enabled?: System.get_env("HYDRA_TELEMETRY_DEV_SEND") == "1"]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :hydra_srt, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console,
  format: "$time [$level] $message $metadata\n",
  level: :debug,
  # level: :notice,
  metadata: [
    :error_code,
    :file,
    :line,
    :pid
  ]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
